# Generated by Django 5.2.7 on 2025-11-22 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbox_app', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rfid_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('client', 'Client')], default='client', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('rfid_code__isnull', False), models.Q(('rfid_code', ''), _negated=True)), fields=('rfid_code',), name='unique_rfid_code'),
        ),
    ]
