# Generated by Django 5.2.7 on 2025-11-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbox_app', '0003_userprofile_rfid_code_userprofile_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('COE', 'College of Engineering'), ('CCIS', 'College of Computing and Information Sciences'), ('CBT', 'College of Business and Technology'), ('CAS', 'College of Arts and Sciences'), ('CTE', 'College of Teacher Education')], default='COE', max_length=10),
        ),
    ]
