# Generated by Django 5.2.7 on 2025-11-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbox_app', '0005_faculty_is_active_rfidregistration_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ['-open_time']},
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Faculty member assigned to this schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='kbox_app.faculty'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='access_granted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='denial_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='kbox_app.roomschedule'),
        ),
    ]
