# Generated by Django 5.2.7 on 2025-11-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbox_app', '0006_alter_transactionlog_options_roomschedule_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidregistration',
            name='room',
        ),
    ]
