# Generated by Django 5.2.7 on 2025-11-24 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbox_app', '0007_remove_rfidregistration_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidregistration',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kbox_app.room'),
            preserve_default=False,
        ),
    ]
