# Generated by Django 5.2.7 on 2025-11-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbox_app', '0008_rfidregistration_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
