# Generated by Django 5.2.7 on 2025-11-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbox_app', '0009_alter_faculty_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomschedule',
            name='day_of_week',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3),
        ),
    ]
