# Generated by Django 5.2.7 on 2025-12-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbox_app', '0010_alter_roomschedule_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomschedule',
            name='day_of_week',
            field=models.CharField(max_length=100),
        ),
    ]
