# Generated by Django 5.2.7 on 2025-12-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbox_app', '0011_alter_roomschedule_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomschedule',
            name='semester',
            field=models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('summer', 'Summer'), ('summer2', 'Summer 2')], default='1st', max_length=10),
        ),
    ]
