# Generated by Django 5.2.7 on 2025-12-07 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbox_app', '0013_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='faculty_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='rfid_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='room_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='rfid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='kbox_app.rfidregistration'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='kbox_app.room'),
        ),
    ]
