# Generated by Django 5.2.7 on 2025-12-07 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbox_app', '0014_transactionlog_faculty_name_transactionlog_rfid_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDoorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_operations', to='kbox_app.room')),
                ('staff_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
