# Generated by Django 5.2.7 on 2025-12-10 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbox_app', '0015_manualdoorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text='e.g., ESP32-1, ESP32-2', max_length=50, unique=True)),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Last known IP address', null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Last time device checked in', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is device enabled in system')),
                ('firmware_version', models.CharField(blank=True, help_text='Current firmware version', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, help_text='Room this device controls', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esp32_devices', to='kbox_app.room')),
            ],
            options={
                'ordering': ['device_name'],
            },
        ),
    ]
